Linking binary to /usr/bin in postinst

diff --git a/package-scripts/oneacct-export/postrm b/package-scripts/oneacct-export/postrm
--- a/package-scripts/oneacct-export/postrm
+++ b/package-scripts/oneacct-export/postrm
@@ -4,6 +4,23 @@
 # after package is uninstalled.
 #
 
+PROGNAME=$(basename $0)
+INSTALLER_DIR=`dirname $0`
+DEST_DIR=/opt/oneacct-export
+CONFIG_DIR=/etc/oneacct-export
+BIN_DIR=/usr/bin
+
+function error_exit
+{
+  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+  exit 1
+}
+
+# clean up links
+if [ -L "$BIN_DIR/oneacct-export" ]; then
+  rm $BIN_DIR/oneacct-export
+fi
+
 echo "oneacct-export has been uninstalled!"
 
 exit 0
